Code/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('myapp.urls')),
    path('myapp/', include(('myapp.urls', 'myapp'), namespace='myapp')),
]

myapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from myapp import views
#from . import views
app_name = 'myapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models



# Create your models here.

#define the user info
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,verbose_name="user")
    nick_name = models.CharField(max_length=20,verbose_name="nick name")
    avatar = models.FileField(upload_to='avatar', default="avatar/default_avatar.png", null=True,blank=True,verbose_name="avatar")
    gender = models.PositiveSmallIntegerField(
        default=2,
        choices=((1, ("Male")), (2, ("Female"))),
        verbose_name="Gender"
    )
    signature = models.CharField(max_length=100,null=True,blank=True,verbose_name="signature")
    email = models.EmailField(max_length=50,null=True,blank=True,verbose_name="email")
    birthday = models.DateField(null=True,blank=True,verbose_name="birthday")


    class Meta:
        verbose_name = "UserInfo"
        verbose_name_plural = verbose_name
        db_table = "va_userinfo"

myapp/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User

from myapp import models




class LoginForm(forms.Form):
    username = forms.CharField(
        label=("Username"),
        widget=forms.TextInput(
            attrs={"id": "login_username", "autocomplete": "new-username"}))

    password = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password',"id": "login_password"}),
    )


class RegisterForm(forms.ModelForm):
    username = forms.CharField(
        label="User name",
        help_text="Only letters can be entered! For login.",
        widget=forms.TextInput(attrs={"id": "register_username", "autocomplete": "new-username"})
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', "id": "register_password"}),
        help_text=password_validation.password_validators_help_text_html()
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text="Enter the same password as before, for verification."
    )
    birthday = forms.DateField(
        label="Birthday",
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    class Meta:
        model = models.UserInfo
        fields = ("username", "nick_name", "gender", "email", "birthday", "password1", "password2", "birthday")
        exclude = ('avatar', 'signature', 'user')


    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1:
            password_validation.validate_password(password1)
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                "The two passwords are inconsistent!",
                code='password_mismatch',
            )
        return password1

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            user = User.objects.get(username=username)
            raise forms.ValidationError("Username already exists!")
        except User.DoesNotExist:
            return username


class UserProfileForm(forms.ModelForm):
    signature = forms.CharField(
        label="Signature",
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 15})
    )

    birthday = forms.DateField(
        label="Birthday",
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    class Meta:
        model = models.UserInfo
        exclude = ("user",)


class AddMessageForm(forms.ModelForm):
    user = forms.CharField(
        label="User",
        widget=forms.HiddenInput()
    )
    to_user = forms.CharField(
        label="To User",
        widget=forms.HiddenInput()
    )



    def clean_user(self):
        user = self.cleaned_data["user"]
        try:
            user = User.objects.get(id=user)
            return user
        except User.DoesNotExist:
            raise forms.ValidationError("User does not exist!")

    def clean_to_user(self):
        to_user = self.cleaned_data["to_user"]
        try:
            user = User.objects.get(id=to_user)
            return user
        except User.DoesNotExist:
            raise forms.ValidationError("User does not exist!")

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect
from django.urls import reverse

def home(request):
    return render(request, 'home.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect(reverse('myapp:home'))
    else:
        form = AuthenticationForm()
    return render(request, 'myapp/login.html', {'login_form': form})

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Log the user in and redirect to home page
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(reverse('myapp:home'))
    else:
        form = UserCreationForm()
    return render(request, 'myapp/sign_in.html', {'register_form': form})

def logout_view(request):
    logout(request)
    return redirect('myapp:home')

templates/myapp/change_password.html
{% load static %}
{% load bootstrap4 %}
{% block title %}
    Profile
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'bootstrap4/bootstrap.min.css' %}">
<style>
    .border-left-radius-self {
        border-top-left-radius: 2.5rem;
        border-bottom-left-radius: 2.5rem;
    }
    .border-right-radius-self {
        border-top-right-radius: 2.5rem;
        border-bottom-right-radius: 2.5rem;
    }
    label {
        font-weight: bold;
        font-size: 1.5rem;
    }
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row" style="height: 400px;">
        <div class="col-6 border border-right-0 border-primary border-left-radius-self h-100">
            <h4 class="text-primary text-center border-bottom border-primary m-2">Login</h4>
            <div>
                <form action="{% url 'myapp:login' %}" method="post" class="mt-5">
                    {% csrf_token %}
                    {% bootstrap_form login_form %}
                    <div class="text-right">
                        <button class="btn btn-outline-primary">Submit</button>
                    </div>
                </form>
            </div>
            <div class="mt-3 text-right">
                <a href="{% url 'myapp:register' %}">Don't have an account yet? Click here to register</a>
            </div>
        </div>
        <div class="col-6 border border-right-radius-self p-0" style="background-image:url({% static 'img/login_right.jpeg' %}); background-size: cover;">
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'bootstrap4/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'bootstrap4/bootstrap.bundle.min.js' %}"></script>
{% endblock %}

templates/myapp/login.html
{% load static %}
{% load bootstrap4 %}
{% block title %}
    Login
{% endblock %}

{% block css %}
<style>
        .border-left-radius-self {
            border-top-left-radius: 2.5rem;
            border-bottom-left-radius: 2.5rem;
        }
        .border-right-radius-self{
            border-top-right-radius: 2.5rem;
            border-bottom-right-radius: 2.5rem;
        }
        label{
            font-weight: bold;
            font-size: 1.5rem;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row" style="height: 400px;">
            <div class="col-6 border border-right-0 border-primary border-left-radius-self h-100">
                <h4 class="text-primary text-center border-bottom border-primary m-2">Login</h4>
                <div>
                    <form action="{% url 'myapp:login' %}" method="post" class="mt-5">
                        {% csrf_token %}
                        {% bootstrap_form login_form %}
                        <div class="text-right">
                            <button class="btn btn-outline-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <div class="mt-3 text-right">
                    <a href="{% url 'myapp:register' %}">Don't have an account yet? Click here to register</a>
                </div>
            </div>
            <div class="col-6 border border-right-radius-self p-0" style="background-image:url({% static 'img/login_right.jpeg' %});background-size: cover;">
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
{% endblock %}

templates/myapp/sign_in.html
{% load static %}
{% load bootstrap4 %}
{% block title %}
    Register
{% endblock %}

{% block css %}
    <style>
        .border-left-radius-self {
            border-top-left-radius: 2.5rem;
            border-bottom-left-radius: 2.5rem;
        }
        .border-right-radius-self{
            border-top-right-radius: 2.5rem;
            border-bottom-right-radius: 2.5rem;
        }
        label{
            font-weight: bold;
            font-size: 1rem;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 border rounded shadow pb-1">
                <h3 class="text-center text-primary">Register</h3>
                <form action="{% url 'myapp:register' %}" method="post">
                    {% csrf_token %}
                    {% bootstrap_form register_form %}
                    <button class="btn btn-outline-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
{% endblock %}